# Generated by Django 6.0 on 2025-12-11 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djangoapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='worker',
            name='phoneNo',
            field=models.CharField(max_length=15, unique=True),
        ),
    ]
