# Generated by Django 6.0 on 2025-12-12 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djangoapp', '0002_alter_worker_phoneno'),
    ]

    operations = [
        migrations.AddField(
            model_name='worker',
            name='discription',
            field=models.CharField(default='added this on <function now at 0x7c5fcdf65120>', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='worker',
            name='price',
            field=models.DecimalField(decimal_places=3, default=999.23, max_digits=11),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='worker',
            name='rating',
            field=models.FloatField(default=5),
            preserve_default=False,
        ),
    ]
