# Generated by Django 6.0 on 2025-12-15 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djangoapp', '0003_worker_discription_worker_price_worker_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='worker',
            name='jobProfile',
            field=models.CharField(choices=[('vehicle', 'mechanic'), ('health', 'doctor'), ('carpenter', 'carpenter'), ('electrician', 'electrician'), ('home', 'home cleaning/services'), ('appliance', 'electronic device'), ('labour', 'manual labour')], default='labour', max_length=30),
        ),
    ]
