# Generated by Django 6.0 on 2025-12-15 13:06

import phonenumber_field.modelfields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djangoapp', '0004_alter_worker_jobprofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='worker',
            name='jobProfile',
            field=models.CharField(choices=[('vehicle', 'mechanic'), ('mechanic', 'health'), ('doctor', 'carpenter'), ('carpenter', 'electrician'), ('electrician', 'home'), ('home cleaning/services', 'appliance'), ('electronic device', 'labour'), ('manual', ' labour')], default=('manual', ' labour'), max_length=30),
        ),
        migrations.AlterField(
            model_name='worker',
            name='phoneNo',
            field=phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None, unique=True),
        ),
    ]
