# Generated by Django 6.0 on 2025-12-15 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djangoapp', '0005_alter_worker_jobprofile_alter_worker_phoneno'),
    ]

    operations = [
        migrations.AlterField(
            model_name='worker',
            name='phoneNo',
            field=models.CharField(max_length=15, unique=True),
        ),
    ]
