# Generated by Django 6.0 on 2025-12-16 12:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('djangoapp', '0006_alter_worker_phoneno'),
    ]

    operations = [
        migrations.RenameField(
            model_name='worker',
            old_name='discription',
            new_name='description',
        ),
    ]
