# Generated by Django 6.0 on 2025-12-16 13:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('djangoapp', '0007_rename_discription_worker_description'),
    ]

    operations = [
        migrations.RenameField(
            model_name='worker',
            old_name='jobProfile',
            new_name='category',
        ),
    ]
