# Generated by Django 6.0 on 2025-12-16 13:31

import multiselectfield.db.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('djangoapp', '0008_rename_jobprofile_worker_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='worker',
            name='subcategory',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('consult', 'be a consultant'), ('fixed', 'Fixed Charges'), ('Book', 'Hourly pay')], default=['consultant'], max_length=20),
        ),
    ]
