# Generated by Django 6.0 on 2025-12-17 13:57

import multiselectfield.db.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('djangoapp', '0009_worker_subcategory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='worker',
            name='subcategory',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('consult', 'be a consultant'), ('fixed', 'Fixed Charges'), ('book', 'Hourly pay')], default=['consultant'], max_length=20),
        ),
    ]
