# Generated by Django 6.0 on 2025-12-17 14:03

import phonenumber_field.modelfields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('djangoapp', '0010_alter_worker_subcategory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='worker',
            name='phoneNo',
            field=phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None, unique=True),
        ),
    ]
