# Generated by Django 6.0 on 2026-01-08 13:54

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djangoapp', '0011_alter_worker_phoneno'),
    ]

    operations = [
        migrations.AlterField(
            model_name='worker',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False, unique=True),
        ),
    ]
