# Generated by Django 6.0 on 2026-01-12 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djangoapp', '0012_customer_dob_customer_gender'),
    ]

    operations = [
        migrations.AddField(
            model_name='worker',
            name='dob',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='worker',
            name='gender',
            field=models.CharField(default=None, max_length=20),
        ),
    ]
