# Generated by Django 6.0 on 2026-01-09 14:16

import django.utils.timezone
import djangoapp.models
import storages.backends.s3
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djangoapp', '0012_alter_worker_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='worker',
            name='imageURL',
            field=models.ImageField(default=django.utils.timezone.now, storage=storages.backends.s3.S3Storage(), upload_to=djangoapp.models.upload_worker_image),
            preserve_default=False,
        ),
    ]
