# Generated by Django 6.0 on 2026-01-09 14:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('djangoapp', '0012_customer_dob_customer_gender'),
        ('djangoapp', '0013_worker_imageurl'),
    ]

    operations = [
    ]
