# Generated by Django 6.0 on 2026-01-12 14:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('djangoapp', '0013_worker_dob_worker_gender'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='worker',
            name='gender',
        ),
    ]
