# Generated by Django 6.0 on 2026-01-12 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djangoapp', '0014_remove_worker_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='worker',
            name='description',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='worker',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=3, default=0, max_digits=11, null=True),
        ),
        migrations.AlterField(
            model_name='worker',
            name='rating',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
    ]
