# Generated by Django 6.0 on 2026-01-09 14:52

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djangoapp', '0014_merge_20260109_1427'),
    ]

    operations = [
        migrations.AlterField(
            model_name='worker',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True),
        ),
    ]
