# Generated by Django 6.0 on 2026-01-09 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djangoapp', '0015_alter_worker_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='worker',
            name='category',
            field=models.CharField(choices=[('vehicle', 'mechanic'), ('carpenter', 'wood work'), ('electrician', 'appliance'), ('manual', ' labour')], default=('manual', ' labour'), max_length=30),
        ),
    ]
