# Generated by Django 6.0 on 2026-01-12 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djangoapp', '0016_alter_worker_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='worker',
            name='subcategory',
        ),
        migrations.AddField(
            model_name='worker',
            name='is_Consult',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='worker',
            name='is_Fixed',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='worker',
            name='is_Hourly',
            field=models.BooleanField(default=True),
        ),
    ]
