# Generated by Django 6.0 on 2026-01-13 13:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('djangoapp', '0017_remove_worker_subcategory_worker_is_consult_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='address',
        ),
    ]
