# Generated by Django 6.0 on 2026-01-17 14:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('djangoapp', '0015_alter_worker_description_alter_worker_price_and_more'),
        ('djangoapp', '0019_alter_customer_gender'),
    ]

    operations = [
    ]
