# Generated by Django 6.0 on 2026-01-17 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djangoapp', '0020_merge_20260117_1440'),
    ]

    operations = [
        migrations.AddField(
            model_name='worker',
            name='gender',
            field=models.CharField(default=None),
        ),
        migrations.AlterField(
            model_name='worker',
            name='price',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=11),
        ),
        migrations.AlterField(
            model_name='worker',
            name='rating',
            field=models.FloatField(default=0),
        ),
    ]
