# Generated by Django 6.0 on 2026-01-17 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djangoapp', '0021_worker_gender_alter_worker_price_alter_worker_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='worker',
            name='gender',
            field=models.CharField(blank=True, default=None, null=True),
        ),
    ]
