# Generated by Django 6.0.1 on 2026-03-14 04:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djangoapp', '0033_alter_worker_sub_categories'),
    ]

    operations = [
        migrations.AddField(
            model_name='worker',
            name='categories',
            field=models.CharField(default='electrician'),
        ),
    ]
