# Generated by Django 6.0.1 on 2026-03-17 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djangoapp', '0034_worker_categories'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='is_working',
        ),
        migrations.RemoveField(
            model_name='worker',
            name='rates',
        ),
        migrations.AlterField(
            model_name='customer',
            name='work_id',
            field=models.UUIDField(blank=True, null=True),
        ),
    ]
