# Generated by Django 6.0.1 on 2026-03-26 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djangoapp', '0035_remove_customer_is_working_remove_worker_rates_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='worker',
            name='location',
            field=models.CharField(default='', null=True),
        ),
    ]
