# Generated by Django 6.0.1 on 2026-04-01 15:44

import djangoapp.models
import storages.backends.s3
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djangoapp', '0036_alter_worker_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='worker',
            name='imageURL',
            field=models.ImageField(blank=True, null=True, storage=storages.backends.s3.S3Storage(), upload_to=djangoapp.models.upload_worker_image),
        ),
    ]
