# Generated by Django 6.0.1 on 2026-04-22 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djangoapp', '0038_alter_customer_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='temp_id',
            field=models.UUIDField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='worker',
            name='temp_id',
            field=models.UUIDField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='history',
            name='is_finished',
            field=models.BooleanField(default=False),
        ),
    ]
