# Generated by Django 6.0.1 on 2026-05-30 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djangoapp', '0039_customer_temp_id_worker_temp_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='location',
            field=models.CharField(default='', null=True),
        ),
    ]
