# Generated by Django 6.0.1 on 2026-05-30 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djangoapp', '0040_customer_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='location',
            field=models.CharField(default='nagpur', null=True),
        ),
    ]
