# Generated by Django 6.0.1 on 2026-06-08 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djangoapp', '0041_alter_customer_location'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='location',
        ),
        migrations.AddField(
            model_name='customer',
            name='address',
            field=models.CharField(default='nagpur', null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='geo_location',
            field=models.CharField(null=True),
        ),
    ]
