# Generated by Django 6.0.1 on 2026-06-08 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djangoapp', '0042_remove_customer_location_customer_address_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='history',
            name='geo_location',
            field=models.CharField(null=True),
        ),
    ]
