# Generated by Django 6.0.1 on 2026-06-17 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djangoapp', '0043_history_geo_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='worker',
            name='address',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='worker',
            name='dob',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='worker',
            name='is_online',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AlterField(
            model_name='worker',
            name='is_working',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
