# Generated by Django 6.0 on 2026-01-08 13:16

import imageserver.models
import storages.backends.s3
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProfileImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profileID', models.IntegerField(unique=True)),
                ('file', models.ImageField(storage=storages.backends.s3.S3Storage(), upload_to=imageserver.models.uploadToUUID)),
                ('uploadedAT', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
