# Generated by Django 6.0 on 2026-01-09 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imageserver', '0002_alter_profileimage_profileid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profileimage',
            name='profileID',
            field=models.UUIDField(db_index=True),
        ),
    ]
