# Generated by Django 5.2.8 on 2025-12-08 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='fullName')),
                ('address', models.CharField(max_length=500)),
                ('phoneNo', models.CharField(max_length=15, unique=True)),
                ('email', models.EmailField(max_length=256, unique=True)),
            ],
        ),
    ]
