# Generated by Django 5.2.8 on 2025-12-10 12:43

import phonenumber_field.modelfields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customerSide', '0002_history'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='phoneNo',
            field=phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None, unique=True),
        ),
    ]
